"""PDF report generation using reportlab - Clean version"""

from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    BaseDocTemplate,
    Flowable,
    Frame,
    HRFlowable,
    ListFlowable,
    ListItem,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

BRAND = colors.HexColor("#6c5ce7")
DARK = colors.HexColor("#16213e")
GRAY = colors.HexColor("#6b6b7b")
LIGHT_BG = colors.HexColor("#f4f3fb")


class ScoreBar(Flowable):
    def __init__(self, label, score, width=160 * mm, height=6 * mm):
        super().__init__()
        self.label = label
        self.score = max(0, min(100, int(score or 0)))
        self.width = width
        self.height = height

    def draw(self):
        c = self.canv
        c.setFont("Helvetica", 9.5)
        c.setFillColor(DARK)
        c.drawString(0, self.height + 2, self.label)
        c.setFont("Helvetica-Bold", 9.5)
        c.drawRightString(self.width, self.height + 2, f"{self.score}/100")

        bar_y = 0
        c.setFillColor(colors.HexColor("#e6e4f5"))
        c.roundRect(0, bar_y, self.width, self.height, self.height / 2, fill=1, stroke=0)

        fill_width = self.width * (self.score / 100.0)
        if fill_width > 0:
            c.setFillColor(BRAND)
            c.roundRect(0, bar_y, max(fill_width, self.height), self.height, self.height / 2, fill=1, stroke=0)

    def wrap(self, availWidth, availHeight):
        return (self.width, self.height + 14)


def _safe(text):
    return "" if text is None else str(text)


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle(name="H1", fontName="Helvetica-Bold", fontSize=22, textColor=DARK, spaceAfter=8, alignment=TA_CENTER))
    ss.add(ParagraphStyle(name="Meta", fontName="Helvetica", fontSize=9, textColor=GRAY, spaceAfter=10))
    ss.add(ParagraphStyle(name="CompanyName", fontName="Helvetica-Bold", fontSize=18, textColor=DARK, spaceAfter=8))
    ss.add(ParagraphStyle(name="SubInfo", fontName="Helvetica", fontSize=10.5, textColor=colors.HexColor("#333333"), leading=15))
    ss.add(ParagraphStyle(name="SectionTitle", fontName="Helvetica-Bold", fontSize=13, textColor=BRAND, spaceBefore=16, spaceAfter=8))
    ss.add(ParagraphStyle(name="Body", fontName="Helvetica", fontSize=10.5, textColor=colors.HexColor("#333333"), leading=15, alignment=TA_LEFT))
    ss.add(ParagraphStyle(name="ListItem", fontName="Helvetica", fontSize=10.5, textColor=colors.HexColor("#333333"), leading=15))
    return ss


def _header_footer(canv: canvas.Canvas, doc):
    canv.saveState()
    canv.setFillColor(BRAND)
    canv.rect(0, A4[1] - 4 * mm, A4[0], 4 * mm, fill=1, stroke=0)
    canv.setFont("Helvetica", 8)
    canv.setFillColor(GRAY)
    canv.drawString(18 * mm, 10 * mm, "Generated by Company Research Assistant")
    canv.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc.page}")
    canv.restoreState()


def generate_pdf(data: dict) -> bytes:
    styles = _styles()
    buf = BytesIO()

    doc = BaseDocTemplate(
        buf,
        pagesize=A4,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="main")
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_header_footer)])

    story = []

    # Title only
    story.append(Paragraph("Company Research Report", styles["H1"]))
    story.append(Spacer(1, 12)) 
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e0e0e0"), spaceAfter=12))

    # Company Name + Info
    story.append(Paragraph(_safe(data.get("companyName") or "Unknown Company"), styles["CompanyName"]))
    story.append(Spacer(1, 8))  # Good spacing after company name

    story.append(Paragraph(
        f"<b>Website:</b> {_safe(data.get('website') or 'N/A')}<br/>"
        f"<b>Phone:</b> {_safe(data.get('phone') or 'N/A')}<br/>"
        f"<b>Address:</b> {_safe(data.get('address') or 'N/A')}",
        styles["SubInfo"],
    ))
    story.append(Spacer(1,10))

    # AI Insight Score
    insight = data.get("insight") or {}
    if insight:
        story.append(Paragraph("AI Insight Score", styles["SectionTitle"]))
        if insight.get("overallScore") is not None:
            story.append(ScoreBar("Overall Score", insight.get("overallScore")))
        if insight.get("marketPosition") is not None:
            story.append(ScoreBar("Market Position", insight.get("marketPosition")))
        if insight.get("digitalPresence") is not None:
            story.append(ScoreBar("Digital Presence", insight.get("digitalPresence")))
        if insight.get("growthPotential") is not None:
            story.append(ScoreBar("Growth Potential", insight.get("growthPotential")))
        if insight.get("insightSummary"):
            story.append(Spacer(1, 8))
            story.append(Paragraph(_safe(insight["insightSummary"]), styles["Body"]))

    # Summary
    if data.get("summary"):
        story.append(Paragraph("Company Summary", styles["SectionTitle"]))
        story.append(Paragraph(_safe(data["summary"]), styles["Body"]))

    # Products
    products = data.get("products") or []
    if products:
        story.append(Paragraph("Products / Services", styles["SectionTitle"]))
        story.append(ListFlowable(
            [ListItem(Paragraph(_safe(p), styles["ListItem"])) for p in products],
            bulletType="bullet", start="•",
        ))

    # Pain Points
    pain_points = data.get("painPoints") or []
    if pain_points:
        story.append(Paragraph("AI-Generated Pain Points", styles["SectionTitle"]))
        story.append(ListFlowable(
            [ListItem(Paragraph(_safe(p), styles["ListItem"])) for p in pain_points],
            bulletType="bullet", start="•",
        ))

    # Competitors
    competitors = data.get("competitors") or []
    if competitors:
        story.append(Paragraph("Competitor Analysis", styles["SectionTitle"]))
        rows = [["Name", "Website"]]
        for c in competitors:
            rows.append([_safe(c.get("name", "")), _safe(c.get("website", "N/A"))])
        table = Table(rows, colWidths=[70 * mm, 90 * mm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), LIGHT_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), DARK),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e0e0e0")),
        ]))
        story.append(table)

    doc.build(story)
    return buf.getvalue()